# autogenerated by ./buildversion.sh
# Tue Aug 30 16:43:02 EST 2011
def get_version():
    """
    Return version string containing global version number and 'build' date
    """
    return "Revision 4265, Tue Aug 30 16:43:02 EST 2011"
